# ASCII logos of French TV channels

# max width = 72
# max heigth = 18

raspitv = ["________________________________________________",
           "    ____                ____       ______ _    _",
           "    /    )              /    )   ,   /    |   / ",
           "---/___ /----__---__---/____/-------/-----|--/--",
           "  /    |   /   ) (_ \` /        /   /      | /  ", 
           "_/_____|__(___(_(__)_/________/___/_______|/____",
           "                                                ",
           "                                                ",
           "Démarrage terminé",
           "Télécommande accessible à l'adresse :",
           "192.168.1.106"]

ch1 = ["dddddddhhhhhyyyyyyyyyyyyyssssssssssssssssssssssssssyyyyyyyyyyyhhhhhhhddd",
       "dddddddhhhhhyyyyyyyyyyyyyssssssssssssssssssssssssssyyyyyyyyyyyhhhhhhhddd",
       "dddddo                yyysssssso              `ssssyyyyyyso+/:.`-hhhhddd",
       "dddddo                yyysssssso              `yyyyyyyyy:       -hhhdddd",
       "dddddo                yyysssssss        sssssssddddddhhh:       -ddddddd",
       "dddddhyyyo       `ssyyhhdddddmdh        hhhhhddddddddhhh:       -ddddddd",
       "dddddddhhs       .mmmmmmmmmmmmdh            `ddddddddhhh:       -ddddddd",
       "ddddddmmmy       .mmmmmmmmmmmmdh            `ddddddddhhh:       -ddddddd",
       "mmmmmmmmmy       .mmmmmmmmmmmmdh        yyyyyddddddddhhh:       -ddddddd",
       "mmmmmmmmmy       .mmmmmmmmmmmmdh        dddddddddddddhhh:       -ddddddd",
       "mmmmmmmmmy       .mmmmmmmmmmmmdh        dddddddddddddhhh:       -ddddddd",
       "mmmmmmmmmmddddddddmmmmmmmmmmmmdddddhhhhhdddddddddddddhhhhyyhhhhhhddddddd",
       "mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmdddddddddddddddddddddddhhhhhhhhhdddddddddd"]

ch2 = ["MMMMMMMMMMMMMMMMMMMMMWXkc,.....':dKWMMMM",
       "MMMMMMMMMMMMMMMMMMWKOd;...........,lONMM",
       "MMMMMMMMMMMMMMMMMWk;.................lKM",
       "MMMMMMMMMMMMMMMMWk'......;okOkd:......:K",
       "MMMMMMMMMMMMMMMMXc......cXMMMMMNd......d",
       "MMMMMMMMMMMMMMMMKl;;;;;c0MMMMMMMK;.....c",
       "MMMMMMMMMMMMMMMMWWNNNNNNWMMMMMMWk'.....o",
       "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWk,.....;0",
       "MWX0kxxk0XWMMMMMMMMMMMMMMMMMWKo'.....,kW",
       "Kxc;,,,,;cxXWMMMMMMMMMMMMMWXd,......:0WM",
       "l,,,,,,,,,,oKWMMMMMMMMMMMXx,......,xXMMM",
       ",,,,,,,,,,,;kWMMMMMMMMMNx;......'oKWMMMM",
       ";,,,,,,,,,,:OWMMMMMMMNk:......'l0WMMMMMM",
       "x:,,,,,,,,:kNMMMMMNOd:.......c0WMMMMMMMM",
       "WKxlc::clxKWMMMMWOc.........ckOOOOOOOOOO",
       "MMWWNXXNWWMMMMMWk'......................",
       "MMMMMMMMMMMMMMMWd.......................",
       "MMMMMMMMMMMMMMMWd......................."]

ch3 = ["MMMMMMMMMMMMMMMMNl....................:X",
       "MMMMMMMMMMMMMMMMNl....................lN",
       "MMMMMMMMMMMMMMMMWOllllllllll;.......'dXM",
       "MMMMMMMMMMMMMMMMMMMMMMMMMMNk;......c0WMM",
       "MMMMMMMMMMMMMMMMMMMMMMMMW0c......;kNMMMM",
       "MMMMMMMMMMMMMMMMMMMMMMMXo'.......lONMMMM",
       "MMMMMMMMMMMMMMMMMMMMMMNo...........;dKWM",
       "MWNKOOO0KNWMMMMMMMMMMMNo';::;,.......,xN",
       "Xkoc::::coONMMMMMMMMMMWXXNWWWX0d;......d",
       "o:::::::::cxNMMMMMMMMMMMMMMMMMMMXl.....'",
       ":::::::::::l0MMMMMMMMMMMMMMMMMMMMO,.....",
       "c::::::::::oXMMMMMMMMMMMMMMMMMMMWk'.....",
       "Oo:::::::cdKWMMMMWXxloONMMMMMMMNk;.....,",
       "WXOxdoodk0NWMMMW0o,....:ok000kd:......,k",
       "MMMMWWWWMMMMMMMNx,...................:OW",
       "MMMMMMMMMMMMMMMMWXxc;,............,lONMM",
       "MMMMMMMMMMMMMMMMMMMWXKd:'......,cxKWMMMM"]

ch4 = ["MMMMMMMMMMMMMMMMMMMMMMMMMMMMK:......dWMM",
       "MMMMMMMMMMMMMMMMMMMMMMMMMMW0c.......dWMM",
       "MMMMMMMMMMMMMMMMMMMMMMMMMWk,........dWMM",
       "MMMMMMMMMMMMMMMMMMMMMMMMNd'.........dWMM",
       "MMMMMMMMMMMMMMMMMMMMMMMKl.....'.....dWMM",
       "MMMMMMMMMMMMMMMMMMMMMWO;....,xo.....dWMM",
       "MMMMMMMMMMMMMMMMMMMNKx'....:0Nd.....dWMM",
       "MNKkxxxOXWMMMMMMMMXl,.....lXMWd.....dWMM",
       "0o;,,,,,:dKWMMMMW0:.....'xNMMWd.....dWMM",
       ":,,,,,,,,,oXMMMNk,.....'dKKKKKl.....lKKK",
       ",,,,,,,,,,c0MMMO,.......''''''.......'''",
       "l,,,,,,,,;dNMMMk'.......................",
       "Kxc;;,;:lONWMMMKdlllllllllllll,.....,lll",
       "MWNK0O0KNWMMMMMMMMMMMMMMMMMMMWd.....oWMM",
       "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMWd.....dWMM",
       "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMWd.....dWMM"]

ch5 = ["MMMMMMMMMMMMMMMMMMXc.................'kM",
       "MMMMMMMMMMMMMMMMMM0;.................'kM",
       "MMMMMMMMMMMMMMMMMMk'.....'clllllllllldKM",
       "MMMMMMMMMMMMMMMMMWo......oNMMMMMMMMMMMMM",
       "MMMMMMMMMMMMMMMMMXc......xNNNNNWMMMMMMMM",
       "MMMMMMMMMMMMMMMMM0;......,;,,,;:ld0NMMMM",
       "MMMMMMMMMMMMMMMMMk'................;dKWM",
       "MWNXK00KXNMMMMMMWd........''''.......,xN",
       "XOxdoooodx0NMMMMWkc::::lx0KXXKOo;......d",
       "kooooooooooONMMMMMWWWWWWMMMMMMMMKc.....'",
       "oooooooooooxKWMMMMMMMMMMMMMMMMMMMO,.....",
       "dooooooooookXMMMMMMMMMMMMMMMMMMMWk'.....",
       "0xooooooodkXWMMMMWKxloONMMMMMMMNk;.....,",
       "WNKOkxkkOKNWMMMW0o,....:okO00kd:......,k",
       "MMMMWWWWMMMMMMMNx,...................:OW",
       "MMMMMMMMMMMMMMMMWXxc;,............,lONMM",
       "MMMMMMMMMMMMMMMMMMMWNKxc,......,cxKWMMMM"]

ch6 = ["      h/`            .///////.           `/h      ",
       "     :NNm+`        `://////:`          `+mNN:     ",
       "     sNNNNm+`     `://////:          `+mNNNNs     ",
       "    `mNNNNNNmo.  .///////:.``      .omNNNNNNm`    ",
       "    :NNNNNNNNNmo-////////////::.`.omNNNNNNNNN:    ",
       "    yNNNNNNNNNNh/////////////////smNNNNNNNNNNy    ",
       "   `mNNNNNNNNNd///////::--:://////+dNNNNNNNNNm`   ",
       "   /NNNNNNNNNN+/////+y:    :y+/////+NNNNNNNNNN/   ",
       "   yNNNNNNNNNd//////dNNy::yNNd//////hNNNNNNNNNy   ",
       "  `NNNNNNNNNNd//////dNNNNNNNNd//////hNNNNNNNNNN`  ",
       "  /NNNNNNNNNNN+/////+hmNNNNmh+/////+mNNNNNNNNNN/  ",
       "  hNNNNNNNNNNNd+//////+osso+//////+dNNNNNNNNNNNh  ",
       " .NNNNNNNNNNNNmms////////////////smmNNNNNNNNNNNN. ",
       " +NNNNNNNNNNNN.+dmyo+////////+oymd+.NNNNNNNNNNNN+ ",
       " hNNNNNNNNNNNh  `/dNmmdhhhhdmmNd/`  hNNNNNNNNNNNh ",
       ".NNNNNNNNNNNN/    `/dNNNNNNNNd/`    /NNNNNNNNNNNN.",
       "oNNNNNNNNNNNN`       :hNNNNh:       `NNNNNNNNNNNNo",
       "dNNNNNNNNNNNy          :hh:          yNNNNNNNNNNNd"]

ch7 = ["                                       -++++++:                         ",
       "    `.-:::::::-.`     `------..-::: `--/++++++/----     `.-::::::-.`    ",
       " `:/+++++++++++++/.   `++++++++++++`.++++++++++++++  `-/++++++++++++/-` ",
       "`/+++++/-..:+++++++`  `++++++++:--- `--/++++++/---- `/+++++/-..-/+++++/`",
       " ``..---.--:+++++++`  `+++++++`        -++++++:     /++++++:....-++++++/",
       "`-///++++++++++++++`  `+++++++         -++++++:     ++++++++++++++++++++",
       "/+++++++:-.`+++++++`  `+++++++         .++++++:     :++++++:............",
       ":++++++/`   +++++++`  .+++++++          :/++++/      :+++++.            "]

ch8 = ["MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNMM",
       "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN                                 mM",
       "MMMMMMMMMMMMMMMMMmhhyyyhdNMMMMMMMMMMN            `:/+++/:`            mM",
       "MMMMMMMMMMMMMd+-          `:oNMMMMMMN         `+mMMMMMMMMMmo`         mM",
       "MMMMMMMMMMMs.               `NMMMMMMN        .mMMMMMdhdMMMMMm.        mM",
       "MMMMMMMMMN-       ./+oo+/-  /MMMMMMMN        yMMMMM-   .NMMMMh        mM",
       "MMMMMMMMM-      /mMMMMMMMMNhmMMMMMMMN        oMMMMM/   -NMMMMs        mM",
       "MMMMMMMMs      sMMMMMMMMMMMMMMMMMMMMN         oMMMMMNdNMMMMMs         mM",
       "MMMMMMMM:     `NMMMMMMMMMMMMMMMMMMMMN          /mMMMMMMMMMm+`         mM",
       "MMMMMMMM:     `NMMMMMMMMMMMMMMMMMMMMN        +NMMMMMhyhNMMMMNo        mM",
       "MMMMMMMMy      -mMMMMMMMMMMMMMMMMMMMN       +MMMMMm.   `dMMMMMo       mM",
       "MMMMMMMMM:      `/ydmNmdy+hMMMMMMMMMN       yMMMMMm.   `dMMMMMh       mM",
       "MMMMMMMMMMo               mMMMMMMMMMN       -NMMMMMMdhdMMMMMMN-       mM",
       "MMMMMMMMMMMmo.           :MMMMMMMMMMN        .yNMMMMMMMMMMMMy.        mM",
       "MMMMMMMMMMMMMMmhs+/:://oymMMMMMMMMMMN          `:oyhdddhyo:`          mM",
       "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN                                 mM",
       "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN                                 mM",
       "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNMM"]

ch9 = [",''''''':xXWMMMMMXl........c0WMMMMMMMNo'''''''''''''''',,;cox0XWMMMMMMMM",
       "c'......,ckNMMMMM0:........,kWMMMMMMW0:................'''''';cokKWMMMMM",
       "k;......';oKWMMMNd'........'lXMMMMMNKd'.........';coxkkOOkkxdl:,';oONMMM",
       "Xl'......':kNMMMKc'.........;OWMMMMOo:.......':dOXWMMMMMMMMMMWN0x:',l0WM",
       "WO;......';o0WMWk,..........'dNMMMNo,'......;dXWMMMMMMMMMMMMMMMMWXx;':OW",
       "MXo'......':kNMXl'..........'cKMMWO;.......;kNMMMMMMN0xddk0NMMMMMMWk;.:O",
       "MWO;......';o0WO;............,kWMXl'......'lXMMMMMMXo,...';xNMMMMMMWx,'l",
       "MMNo'......':kKd'.....''..'..'lXWk;.......'oNMMMMMMKc.....,oXMMMMMMM0:.,",
       "MMMO:......';od:.....';;'.....;OXl'........c0WMMMMMWKxlccokXWMMMMMMMKc.'",
       "MMMNd'......'::'.....'lo;.....'od,.........'l0WMMMMMMWWWWWMMMMMMMMMMKc.'",
       "MMMM0:......',,......,x0c.....',,'..........';oOXNWMMMMMMWNXNMMMMMMWO;.,",
       "MMMMNd'......''.....':ONd'.................',,,;codxxdddollxXMMMMMMXo''l",
       "MMMMM0:.............'oXWO;..........'......;xKKKKKK0xc::coONWMMMMMNd,.:0",
       "MMMMMNx,...........';kNMXl'............,;,.'c0WMMMMMWWNNNWMMMMMMW0l'':OW",
       "MMMMMMKc...........'c0WMWx,...........'l0x;'';d0NWMMMMMMMMMMMWXOo;',lKWM",
       "MMMMMMWx,..........,dXMMM0:...........;OWW0o;'',:oxkO00000Okdl:'',cONMMM",
       "MMMMMMMKc'........':kWMMMXo'.........'dNMMMWKxl;,'.''',,'''..';cd0NMMMMM",
       "MMMMMMMWd'..'.....'lKWMMMWx,.....'...:OMMMMMMWNKko:;'''..',;cdOXWMMMMMMM"]

ch19 = ["MMMMMMMMMMMMMMMMMMMMMMMXo'....lKWMMMMMMM",
        "MMMMMMMMMMMMMMMMMMMMMW0c',oOd;':OWMMMMMM",
        "MMMMMMMMMMMMMMMMMMMMMWX0O0KKK0O0XWMMMMMM",
        "MMMMMMMMMMMMMMMMMMWKOkoc;,''',;:lx0NMMMM",
        "MMMMMMMMMMMMMMMMNkc'...............:xXMM",
        "MMMMMMMMMMMMMMW0c......,ldxkkdl;.....:OW",
        "MMMMMMMMMMMMMW0;.....;kNWMMMMMMNOc....,k",
        "MMMMMMMMMMMMMXc....cOXMMMMMMMMMMMNo....;",
        "WNXXXXXNWMMMMO'...,OMMMMMMMMMMMMMMK:....",
        "X00OOO00XWMMMk'...;KMMMMMMMMMMMMMMXc....",
        "0OOO0OO00XWMM0,...'kWWMMMMMMMMMMMM0;....",
        "0OO0OOOO0XWMMNo....;oOWMMMMMMMMMW0:....c",
        "NK00O00KXWMMMMXl.....'lOXWMMMWN0o,....:0",
        "MWNNNNNWMMMMMMMNx,......,:lllc,.....'oXM",
        "MMMMMMMMMMMMMMMMWXxc;'...........':dKWMM",
        "MMMMMMMMMMMMMMMMMMMNX0o:'.....';oONMMMMM"]

List = [ch1, ch2, ch3, ch4, ch5, ch6, ch7, ch8, ch9, [], [], [], [], [], [], [], [], [], ch19, [], [], [], [], [], [], [], [], [], [], [], [], [], ch3, [], []]